<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:17:59 +0000
// --------------------------------------------------------------------------------

$l['mod_tools'] = 'Инструмент модератора';
$l['thread_tools'] = 'Инструменты тем';
$l['thread_tools_desc'] = ' .';
$l['add_thread_tool'] = 'Добавить инструмент темы';
$l['add_new_thread_tool'] = 'Добавить новый инструмент темы';
$l['add_thread_tool_desc'] = 'Здесь вы можете добавить новый инструмент модерации тем пользователей. Этот инструмент будет доступен как из внутренней модерации тем, так и перечисленные при модерации инструментов по умолчанию.';
$l['post_tools'] = 'Инструменты сообщения';
$l['post_tools_desc'] = 'Пользовательские инструменты модератора позволяет создавать комбинации действий модератора, которые могут быть использованы и для тем и для сообщений. Они могут быть использованы как инструменты по умолчанию при управлении форумом. Здесь вы можете управлять инструментами сообщений пользователя.';
$l['add_post_tool'] = 'Добавить инструмент сообщения';
$l['add_new_post_tool'] = 'Добавить инструмент нового сообщения';
$l['add_post_tool_desc'] = 'Здесь вы можете добавить пользовательский инструмент модерации сообщения. Этот инструмент будет доступен изнутри самих тем, и перечислены в списке интсрументов модерации.';
$l['edit_post_tool'] = 'Редактировать инструмент сообщения';
$l['edit_post_tool_desc'] = 'Здесь вы можете редактировать настройки и действия Инструмента сообщений.';
$l['edit_thread_tool'] = 'Редактировать инструмент темы';
$l['edit_thread_tool_desc'] = 'Здесь вы можете редактировать настройки и действия Инструмента темы.';
$l['no_thread_tools'] = 'Нет настроек тем на вашем форуме.';
$l['no_post_tools'] = 'Нет настроек сообщений на вашем форуме.';
$l['confirm_thread_tool_deletion'] = 'Вы уверены, что хотите удалить этот инструмент темы?';
$l['confirm_post_tool_deletion'] = 'Вы уверены, что хотите удалить этот инструмент сообщения?';
$l['success_post_tool_deleted'] = 'Выбранный инструмент модерации сообщений был успешно удален.';
$l['success_thread_tool_deleted'] = 'Выбранный инструмент модерации тем был успешно удален.';
$l['error_invalid_post_tool'] = 'Указанный инструмент сообщений не существует.';
$l['error_invalid_thread_tool'] = 'Указанный инструмент тем не существует.';
$l['general_options'] = 'Основные параметры';
$l['short_description'] = 'Краткое описание';
$l['available_in_forums'] = 'Доступно в форумах';
$l['available_to_groups'] = 'Доступно в группах';
$l['show_confirmation'] = 'Показать страницу подтверждения';
$l['save_thread_tool'] = 'Сохранить инструмент темы';
$l['title'] = 'Заголовок';
$l['thread_moderation'] = 'Модерация темы';
$l['approve_unapprove'] = 'Одобрить/Запретить тему?';
$l['no_change'] = 'Без изменений';
$l['approve'] = 'Одобриь';
$l['unapprove'] = 'Запретить';
$l['stick'] = 'Прикрепить';
$l['unstick'] = 'Открепить';
$l['open'] = 'Открыть';
$l['close'] = 'Закрыть';
$l['toggle'] = 'Свенуть';
$l['days'] = 'Дней';
$l['no_prefix'] = 'Без префикса';
$l['restore'] = 'Восстановить';
$l['softdelete'] = 'Предудаление';
$l['forum_to_move_to'] = 'Форум для переноса:';
$l['leave_redirect'] = 'Оставить перенаправление?';
$l['delete_redirect_after'] = 'Удалить перенаправления после';
$l['do_not_move_thread'] = 'Не перемещать тему';
$l['do_not_copy_thread'] = 'Не копировать тему';
$l['move_thread'] = 'Переместить тему?';
$l['move_thread_desc'] = 'Если переносится тема(ы), то "удалить перенаправления после ... дней" заполняется только, если редирект останется.';
$l['forum_to_copy_to'] = 'Форум для копирования:';
$l['copy_thread'] = 'Копировать тему?';
$l['open_close_thread'] = 'Открыть/Закрыть тему?';
$l['stick_unstick_thread'] = 'Закрепить/открепить тему?';
$l['softdelete_restore_thread'] = 'Преудаление/восстановление темы?';
$l['delete_thread'] = 'Удалить тему навсегда?';
$l['merge_thread'] = 'Объединить тему?';
$l['merge_thread_desc'] = 'Только при использовании встроенной модерации.';
$l['delete_poll'] = 'Удалить опрос?';
$l['delete_redirects'] = 'Удалить перенаправления?';
$l['remove_subscriptions'] = 'Удалить подписки тем?';
$l['recount_rebuild'] = 'Пересчитать & Перестроить?';
$l['apply_thread_prefix'] = 'Применить префикс темы?';
$l['new_subject'] = 'Новая тема?';
$l['new_subject_desc'] = '{subject} представляет собой оригинальную тему. {username} представляет собой имя модератора.';
$l['add_new_reply'] = 'Добавить новый ответ';
$l['add_new_reply_desc'] = 'Оставьте пустым если нет ответа.';
$l['reply_subject'] = 'Тема ответа.';
$l['reply_subject_desc'] = 'Only used if a reply was made.<br />{subject} represents the original subject. {username} represents the moderator\'s username.';
$l['success_mod_tool_created'] = 'The moderation tool has been created successfully.';
$l['success_mod_tool_updated'] = 'The moderation tool has been updated successfully.';
$l['inline_post_moderation'] = 'Inline Post Moderation';
$l['delete_posts'] = 'Удалить сообщения навсегда?';
$l['merge_posts'] = 'Объединить сообщения?';
$l['merge_posts_desc'] = 'Только при использовании встроенной модерации.';
$l['approve_unapprove_posts'] = 'Approve/unapprove posts?';
$l['softdelete_restore_posts'] = 'Soft delete/restore posts?';
$l['split_posts'] = 'Разделить сообщение';
$l['split_posts2'] = 'Split posts?';
$l['do_not_split'] = 'Do not split posts';
$l['split_to_same_forum'] = 'Split to same forum';
$l['close_split_thread'] = 'Close split thread?';
$l['stick_split_thread'] = 'Stick split thread?';
$l['unapprove_split_thread'] = 'Unapprove split thread?';
$l['split_thread_prefix'] = 'Split thread prefix';
$l['split_thread_subject'] = 'Split thread subject';
$l['split_thread_subject_desc'] = '{subject} represents the original subject. Only required if splitting posts.';
$l['add_new_split_reply'] = 'Add reply to split thread';
$l['add_new_split_reply_desc'] = 'Leave blank for no reply.';
$l['split_reply_subject'] = 'Reply subject';
$l['split_reply_subject_desc'] = 'Only used if a reply is made';
$l['save_post_tool'] = 'Save Post Tool';
$l['send_private_message'] = 'Send Private Message';
$l['private_message_message'] = 'Message';
$l['private_message_message_desc'] = 'Message to send to the author of the thread. Leave empty to disable this feature.';
$l['private_message_subject'] = 'Subject';
$l['private_message_subject_desc'] = 'Enter the subject of the Private Message.';
$l['error_missing_title'] = 'Please enter a name for this tool.';
$l['error_missing_description'] = 'Please enter a short description for this tool.';
$l['error_no_forums_selected'] = 'Please select the forums in which this tool will be available.';
$l['error_no_groups_selected'] = 'Please select the groups to which this tool will be available.';
$l['error_forum_is_category'] = 'You can\'t pick a category-type forum as a destination forum.';
