<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:23:36 +0000
// --------------------------------------------------------------------------------

$l['statistics'] = 'Statistics';
$l['overall_statistics'] = 'Overall Statistics';
$l['overall_statistics_desc'] = 'Here you can view overall statistics on your forum. All times are in UTC.';
$l['date_range'] = 'Date Range';
$l['date'] = 'Date';
$l['users'] = 'Users';
$l['threads'] = 'Threads';
$l['posts'] = 'Posts';
$l['from'] = 'From';
$l['to'] = 'to';
$l['increase'] = 'Increase';
$l['no_change'] = 'No Change';
$l['decrease'] = 'Decrease';
$l['error_no_results_found_for_criteria'] = 'We could not find any results for the date range you provided. Please try a different date range.';
$l['error_no_statistics_available_yet'] = 'We\'re sorry, there are currently no statistics data available for your forum yet.';
