<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:23:41 +0000
// --------------------------------------------------------------------------------

$l['system_health'] = 'Работоспособность системы';
$l['system_health_desc'] = 'Здесь вы можете просматривать информацию о работоспособности вашей системы.';
$l['utf8_conversion'] = 'UTF-8 конвертация';
$l['utf8_conversion_desc'] = 'Вы сейчас сконвертируете таблицы базы данных в формат UTF-8. Имейте в виду, что этот процесс может занять до нескольких часов в зависимости от размера вашего форума и этой таблицы. Когда процесс будет завершен, вы будете возвращены к  главной страницы конвертации UTF-8.';
$l['utf8_conversion_desc2'] = 'Этот инструмент проверяет таблицы базы данных, чтобы убедиться, что они находятся в формате UTF-8 и позволяет конвертировать их, если они таковыми не являются.';
$l['convert_all'] = 'Ковертировать ВСЕ';
$l['converting_to_utf8'] = 'MyBB в настоящее время конвертирует "{1}" таблицу в UTF-8 кодировку языка из {2} кодировки.';
$l['convert_to_utf8'] = 'Вы собираетесь преобразовать "{1}" таблицу в UTF-8 кодировку языка из {2} кодировки.';
$l['convert_all_to_utf'] = 'Вы собираетесь преобразовать все таблицы в UTF-8 кодировку языка из {1} кодировки.';
$l['convert_all_to_utf8mb4'] = 'Вы собираетесь преобразовать все таблицы в 4-х байтную UTF-8 кодировку Unicode языка из {1} кодировки.';
$l['converting_to_utf8mb4'] = 'MyBB в настоящее время конвертирует "{1}" таблицу 4 байтную UTF-8 Unicode кодировку языка их {2} кодировки.';
$l['please_wait'] = 'Пожалуйста, подождите...';
$l['converting_table'] = 'Преобразование таблицы:';
$l['convert_table'] = 'Преобразовать таблицу';
$l['convert_tables'] = 'Преобразовать все таблицы';
$l['convert_database_table'] = 'Преобразование таблицы базы данных';
$l['convert_database_tables'] = 'Преобразование всех таблиц баз данных';
$l['table'] = 'Таблица';
$l['status_utf8'] = 'UTF-8 статус';
$l['status_utf8mb4'] = '4-Byte UTF-8 поддержка<br />(требуется MySQL 5.5.3 или выше)';
$l['not_available'] = 'Недоступно';
$l['all_tables'] = 'Все таблицы';
$l['convert_now'] = 'Конвертировать сейчас';
$l['totals'] = 'Всего';
$l['attachments'] = 'Вложения';
$l['total_database_size'] = 'Общий размер базы данных';
$l['attachment_space_used'] = 'Пространство, использованное вложениями';
$l['total_cache_size'] = 'Общий размер кэша';
$l['estimated_attachment_bandwidth_usage'] = 'Расчетное использование полосы пропускания вложений';
$l['max_upload_post_size'] = 'Максимальный размер Upload / POST ';
$l['average_attachment_size'] = 'Средний размер вложений';
$l['stats'] = 'Статистика';
$l['task'] = 'Задача';
$l['run_time'] = 'Продолжительность';
$l['next_3_tasks'] = 'Следующие 3 задачи';
$l['no_tasks'] = 'Нет задач, запущенных в данный момент.';
$l['backup_time'] = 'Время бэкапа';
$l['no_backups'] = 'В настоящее время нет сделанных резервные копий.';
$l['existing_db_backups'] = 'Существующие архивы БД';
$l['writable'] = 'Для записи доступно';
$l['not_writable'] = 'Не доступно для записи';
$l['please_chmod_777'] = 'Пожалуйста, измените права CHMOD на 777.';
$l['chmod_info'] = 'Пожалуйста, измените настройки CHMOD на те, что указаны ниже файла. Для получения дополнительной информации о правах CHMOD см';
$l['file'] = 'Файл';
$l['location'] = 'Расположение';
$l['settings_file'] = 'Параметры файла';
$l['config_file'] = 'Файл конфигурации';
$l['file_upload_dir'] = 'Директория загрузки файлов';
$l['avatar_upload_dir'] = 'Директория загрузки аватаров';
$l['language_files'] = 'Файлы языка';
$l['backup_dir'] = 'Каталог архивов';
$l['cache_dir'] = 'Каталог кэша';
$l['themes_dir'] = 'Каталог тем';
$l['chmod_files_and_dirs'] = 'CHMOD файлов и директорий';
$l['notice_process_long_time'] = 'Этот процесс может занять до нескольких часов в зависимости от размера вашего форума и этой таблицы. <strong>Настоятельно рекомендуется создать резервную копию базы данных, так как этот процесс не может быть отменен.</strong>';
$l['notice_mb4_warning'] = 'Поддержка 4-Byte UTF-8 требует MySQL 5.5.3 или выше. вы не будете иметь возможность импортировать базу данных на сервере MySQL с другой версии.';
$l['check_templates'] = 'Проверка шаблонов';
$l['check_templates_desc'] = 'Проверьте все установленные шаблоны на предмет известных проблем безопасности.';
$l['check_templates_title'] = 'Проверка безопасности шаблона';
$l['check_templates_info'] = 'Этот процесс будет проверять ваши шаблоны на проблемы безопасности, которые могут повлиять на ваш форум и сервер. Это может занять некоторое время, если вы установили много тем.
<br /><br />Для старта процесса нажмите ниже кнопку \'Продолжить\'.';
$l['check_templates_info_desc'] = 'The templates below matched known security issues. Please review them.';
$l['full_edit'] = 'Full Edit';
$l['error_chmod'] = 'of the required files and directories do not have proper CHMOD settings.';
$l['error_invalid_table'] = 'The specified table does not exist.';
$l['error_db_encoding_not_set'] = 'Your current setup of MyBB is not setup to use this tool yet. Please see the <a href="http://docs.mybb.com/Utf8_setup.html">MyBB Docs</a> for more information on how to set it up.';
$l['error_not_supported'] = 'Your current Database Engine is not supported by the UTF-8 Conversion Tool.';
$l['error_invalid_input'] = 'There was a problem checking the templates. Please try again or contact the MyBB Group for support.';
$l['error_master_templates_altered'] = 'The Master Templates have been altered. Please contact the MyBB Group for support on how to alter these.';
$l['error_utf8mb4_version'] = 'Your MySQL version doesn\'t support 4-Byte UTF-8 encoding.';
$l['warning_multiple_encodings'] = 'It is recommend not to use different encodings in your database. This may cause unexpected behavior or MySQL errors.';
$l['warning_utf8mb4_config'] = 'For full 4-Byte UTF-8 support you need to change <i>$config[\'database\'][\'encoding\'] = \'utf8\';</i> to <i>$config[\'database\'][\'encoding\'] = \'utf8mb4\';</i> in your inc/config.php.';
$l['success_templates_checked'] = 'Templates checked successfully - no security issues were found!';
$l['success_all_tables_already_converted'] = 'All tables have already been converted or are already in UTF-8 format.';
$l['success_table_converted'] = 'The selected table "{1}" has been converted to UTF-8 successfully.';
$l['success_chmod'] = 'All of the required files and directories have the proper CHMOD settings.';
