<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:22:58 +0000
// --------------------------------------------------------------------------------

$l['file_verification'] = ' Проверка файла';
$l['checking'] = 'Проверяется...';
$l['file_verification_message'] = 'This process will check all MyBB default files to check for validity. Press Yes to continue.<br /> <small>Please note, this process can not differentiate between custom modifications and actual corruption in files. Therefore you should take caution in reverting files this process returns as "corrupt".</small>';
$l['error_communication'] = 'Существует проблема обмена с MyBB сервером. Пожалуйста, повторите попытку через несколько минут.';
$l['file'] = 'Файл';
$l['no_corrupt_files_found'] = 'Congratulations! No corrupt files have been found on your installation.
Поздравления! Поврежденных файлов в вашей установке найдено  не было.';
$l['found_problems'] = 'Найденные проблемы';
$l['no_problems_found'] = 'Проблем не обнаружено';
$l['changed'] = 'Изменено';
$l['missing'] = 'Отсутствует';
$l['status'] = 'Статус';
