<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:24:07 +0000
// --------------------------------------------------------------------------------

$l['user_group_promotions'] = 'User Group Promotions';
$l['user_group_promotions_desc'] = 'Here you can manage User Group Promotions.';
$l['edit_promotion'] = 'Редактировать акцию';
$l['edit_promotion_desc'] = 'Here you can edit promotions which are automatically run on your board.';
$l['add_new_promotion'] = 'Добавить новую акцию';
$l['add_new_promotion_desc'] = 'Here you can create new promotions which are automatically run on your board.';
$l['title'] = 'Заголовок';
$l['short_desc'] = 'Краткое описание';
$l['post_count'] = 'Число постов';
$l['thread_count'] = 'Число тем';
$l['reputation'] = 'Репутация';
$l['referrals'] = 'Рефералы';
$l['time_registered'] = 'Time Registered';
$l['time_online'] = 'Время в сети';
$l['promo_requirements'] = 'Promotion Requirements';
$l['promo_requirements_desc'] = 'Select which criteria must be met for this promotion. Удерживая CTRL выбирите несколько значений.';
$l['greater_than_or_equal_to'] = 'Больше или равно';
$l['greater_than'] = 'Больше, чем';
$l['equal_to'] = 'Равно';
$l['less_than_or_equal_to'] = 'Меньше или равно';
$l['less_than'] = 'Меньше, чем';
$l['reputation_count'] = 'Число репутации';
$l['reputation_count_desc'] = 'Enter the amount of reputation to be required. Reputation must be selected as a required value for this to be included. Select the type of comparison for reputation.';
$l['referral_count'] = 'Число рефералов';
$l['referral_count_desc'] = 'Enter the number of referrals required. Referral count must be selected as a required value for this to be included. Select the type of comparison for referrals.';
$l['warning_points'] = 'Баллов предупреждений';
$l['warning_points_desc'] = 'Enter the number of warning points required. Warning Points must be selected as a required value for this to be included. Select the type of comparison for warning points.';
$l['post_count_desc'] = 'Введите необходимое число сообщений. Для этого число сообщений должно быть выбрано в качестве требуемого значения. Выберите для сообщения тип сравнения.';
$l['thread_count_desc'] = 'Enter the number of threads required. Thread count must be selected as a required value for this to be included. Select the type of comparison for threads.';
$l['hours'] = 'Часов';
$l['days'] = 'Дней';
$l['weeks'] = 'Недель';
$l['months'] = 'Месяцев';
$l['years'] = 'Лет';
$l['time_registered_desc'] = 'Enter the number of hours, days, weeks, months, or years that this user must have been registered for. Time registered must be selected as a required value for this to be included. Select whether the time registered should be counted in hours, days, weeks, months, or years.';
$l['time_online_desc'] = 'Введите количество часов, дней, недель, месяцев или лет, которое этот пользователь должен бы быть на сайте. Время в сети должно быть выбрано в качестве требуемого значения для этого. Выберите время ,которое проводит в сети, оно должно быть указано в часах, днях, неделях, месяцах или годах.';
$l['all_user_groups'] = 'Все группы пользователя';
$l['orig_user_group'] = 'Исходная группа пользователя';
$l['orig_user_group_desc'] = 'Select which user group or user groups that the user must be in for the promotion to run. Используйте клавишу CTRL для выбора множественныз значений.';
$l['new_user_group'] = 'Новая группа пользователя';
$l['new_user_group_desc'] = 'Select the user group that the user will be moved into after this promotion.';
$l['primary_user_group'] = 'Первичная группа пользователя';
$l['secondary_user_group'] = 'Вторичная группа пользователя';
$l['user_group_change_type'] = 'Изменить тип группы';
$l['user_group_change_type_desc'] = 'Select \'Primary User Group\' if the user should have their primary user group changed to the new user group. Select \'Secondary User Group\' if the user should have the new user group added as an secondary user group to their profile.';
$l['enabled'] = 'Доступно?';
$l['enable_logging'] = 'Доступно логирование?';
$l['promotion_logs'] = 'Promotion Logs';
$l['view_promotion_logs'] = 'View Promotion Logs';
$l['view_promotion_logs_desc'] = 'Here you can view logs of promotions previously run.';
$l['promoted_user'] = 'Promoted User';
$l['time_promoted'] = 'Time Promoted';
$l['no_promotion_logs'] = 'There are currently no promotions logged.';
$l['promotion_manager'] = 'Promotions Manager';
$l['promotion'] = 'Promotion';
$l['disable_promotion'] = 'Disable Promotion';
$l['enable_promotion'] = 'Enable Promotion';
$l['delete_promotion'] = 'Delete Promotion';
$l['no_promotions_set'] = 'There are currently no set promotions.';
$l['update_promotion'] = 'Save Promotion';
$l['multiple_usergroups'] = 'Multiple User Groups';
$l['secondary'] = 'Secondary';
$l['primary'] = 'Primary';
$l['error_no_promo_id'] = 'You did not enter a promotion id';
$l['error_invalid_promo_id'] = 'You did not enter a valid promotion id';
$l['error_no_title'] = 'You did not enter a title for this promotion';
$l['error_no_desc'] = 'You did not enter a description for this promotion';
$l['error_no_requirements'] = 'Вы не выбрали, по крайней мере, одно требование';
$l['error_no_orig_usergroup'] = 'Вы не выбрали по крайней мере одну исходную группу пользователей';
$l['error_no_new_usergroup'] = 'You did not select at least one new user group for this promotion';
$l['error_no_usergroup_change_type'] = 'You did not select at least one user group change type for this promotion';
$l['success_promo_disabled'] = 'The selected group promotion has been disabled successfully.';
$l['success_promo_deleted'] = 'The selected group promotion has been deleted successfully.';
$l['success_promo_enabled'] = 'The selected group promotion has been enabled successfully.';
$l['success_promo_updated'] = 'The selected group promotion has been updated successfully.';
$l['success_promo_added'] = 'The promotion has been created successfully.';
$l['confirm_promo_disable'] = 'Are you sure you want to disable this promotion?';
$l['confirm_promo_deletion'] = 'Are you sure you wish to delete this promotion?';
