<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:15:40 +0000
// --------------------------------------------------------------------------------

$l['nav_online'] = 'Кто онлайн';
$l['nav_onlinetoday'] = 'Кто сегодня был онлайн';
$l['viewing_announcements'] = 'Просмотр объявлений <a href="{1}">{2}</a>';
$l['viewing_announcements2'] = 'Просмотр объявлений';
$l['viewing_attachment'] = 'Просмотр вложений';
$l['viewing_attachment2'] = 'Просмотр <a href="attachment.php?aid={1}" target="_blank">вложений</a> в теме <a href="{3}">{2}</a>';
$l['viewing_calendar'] = 'Просмотр <a href="calendar.php">календаря</a>';
$l['viewing_event'] = 'Просмотр событий';
$l['viewing_event2'] = 'Просмотр событий <a href="{1}">{2}</a>';
$l['adding_event'] = '<a href="calendar.php?action=addevent">Добавить событие</a>';
$l['editing_event'] = 'Редактирование события';
$l['viewing_contact_us'] = 'Просмотр <a href="contact.php">контактной информации</a>';
$l['editing_post'] = 'Редактирование сообщения';
$l['viewing_forum'] = 'Просмотр форума';
$l['viewing_forum2'] = 'Просмотр форума <a href="{1}">{2}</a>';
$l['forum_redirect_to'] = 'Перенаправления к <a href="{1}">{2}</a>';
$l['viewing_index'] = '{1} <a href="index.php">Main Index</a>';
$l['activating_account'] = 'Активация учетной записи';
$l['viewing_profile'] = 'Просмотр профиля';
$l['viewing_profile2'] = 'Просмотр профиля <a href="{1}">{2}</a>';
$l['registering'] = '<a href="member.php?action=register">Зарегистрированные</a>';
$l['logging_in'] = '<a href="member.php?action=login">Вошедшие</a>';
$l['logging_in_plain'] = 'Вошедшие';
$l['logging_out'] = 'Вышедшие';
$l['emailing_user'] = 'Emailing a User';
$l['rating_user'] = 'Рэйтинг пользователей';
$l['viewing_memberlist'] = 'Просмотр <a href="memberlist.php">списка зарегистрированнных пользователей</a>';
$l['viewing_whoposted'] = 'Просмотр кто постил';
$l['viewing_whoposted2'] = 'Просмотр кто отвечал в тему <a href="{1}">{2}</a>';
$l['marking_read'] = '<a href="misc.php?action=markread&amp;my_post_key={1}">Отметка форума прочитанным</a>';
$l['viewing_helpdocs'] = 'Просмотр <a href="misc.php?action=help">документов помощи</a>';
$l['viewing_buddylist'] = 'Просмотр <a href="#" onclick="MyBB.popupWindow(\'/misc.php?action=buddypopup&amp;modal=1\'); return false;">Buddy List</a>';
$l['viewing_smilies'] = 'Просмотр страницы <a href="misc.php?action=smilies">списка смайликов</a>';
$l['viewing_syndication'] = 'Просмотр <a href="misc.php?action=syndication">RSS Syndication</a> ';
$l['replying_thread'] = 'Ответ на тему';
$l['replying_thread2'] = 'Ответ на тему <a href="{1}">{2}</a>';
$l['posting_thread'] = 'Posting New Thread';
$l['posting_thread2'] = 'Posting New Thread in <a href="{1}">{2}</a>';
$l['viewing_wol'] = 'Просмотр <a href="online.php">кто онлайн</a>';
$l['viewing_woltoday'] = 'Просмотр <a href="online.php?action=today">кто сегодня был на форуме</a>';
$l['creating_poll'] = 'Создание нового опроса';
$l['editing_poll'] = 'Редактирование опроса';
$l['viewing_pollresults'] = 'Просмотр результатов опроса';
$l['voting_poll'] = 'Voting on a Poll';
$l['using_modtools'] = 'Using Moderator Tools';
$l['sending_pm'] = 'Отправить личное сообщение';
$l['reading_pm'] = 'Прочитать личное сообщение';
$l['editing_pmfolders'] = 'Редактировать папку ЛС';
$l['using_pmsystem'] = 'Использовать ситему ЛС';
$l['reporting_post'] = 'Reporting a Post';
$l['searching_forum'] = '<a href="search.php">Поиск</a> {1}';
$l['reading_thread'] = 'Reading Thread';
$l['reading_thread2'] = 'Reading Thread <a href="{1}">{2}</a> {3}';
$l['viewing_team'] = 'Просмотр команды форума';
$l['viewing_stats'] = 'Просмотр статистики форума';
$l['updating_profile'] = '<a href="usercp.php?action=profile">Обновление профиля</a>';
$l['updating_options'] = '<a href="usercp.php?action=options">Обновление опций</a>';
$l['editing_signature'] = '<a href="usercp.php?action=editsig">Редактирование подписи</a>';
$l['changing_avatar'] = '<a href="usercp.php?action=avatar">Изменение аватара</a>';
$l['viewing_subscriptions'] = 'Viewing <a href="usercp.php?action=subscriptions">Подписка на тему</a>';
$l['editing_pad'] = 'Editing <a href="usercp.php">Personal Pad</a>';
$l['editing_password'] = 'Editing <a href="usercp.php?action=password">Пароль</a>';
$l['user_cp'] = 'Просмотр <a href="usercp.php">панели управления пользователя</a>';
$l['viewing_portal'] = 'Просмотр страницы <a href="portal.php">портала</a> ';
$l['viewing_noperms'] = 'Viewing No Permissions Page';
$l['unknown_location'] = '<a href="{1}">неопознанное расположение</a>';
$l['giving_reputation'] = 'Giving Reputation to <a href="{1}">{2}</a>';
$l['viewing_reputation_report'] = 'Просмотр <a href="{1}">{2} репутаций</a>';
$l['viewing_reputation_report2'] = 'Просмотр репутаций';
$l['member_resendactivation'] = 'Получение Email повторной активация учетной записи ';
$l['member_lostpw'] = 'Получение <a href="member.php?action=lostpw">забытого пароля</a>';
$l['sending_thread'] = 'Отправка темы другу';
$l['guest'] = 'Гость';
$l['page'] = 'Страница';
$l['users_online'] = 'Кто онлайн';
$l['on_username'] = 'Username';
$l['time'] = 'Время';
$l['location'] = 'Расположение';
$l['online_today'] = 'Кто сегодня был на форуме';
$l['refresh_page'] = 'Обновить эту страницу';
$l['online_online_plural'] = 'users';
$l['online_online_singular'] = 'user';
$l['online_member_plural'] = 'members';
$l['online_member_singular'] = 'member';
$l['online_anon_plural'] = 'are';
$l['online_anon_singular'] = 'is';
$l['online_guest_plural'] = 'guests';
$l['online_guest_singular'] = 'guest';
$l['online_count'] = '{1} {2} active in the past {3} minutes ({4} {5}, {6} of whom {7} invisible, and {8} {9}).';
$l['ip'] = 'IP:';
$l['resolves_to'] = 'Хост:';
$l['if_resolvable'] = '(if resolvable)';
$l['admin_options'] = 'Admin Options';
$l['search_regip_users'] = 'Поиск пользователей, которые зарегистрировались с этим IP';
$l['search_postip_users'] = 'Поиск пользователей, которые постили с этим IP';
$l['lookup'] = '[Lookup]';
$l['member_online_today'] = '<strong>1</strong>зарегистрированный был на сайте сегодня';
$l['members_were_online_today'] = '<strong>{1}</strong> зарегистрированных были на сайте сегодня';
$l['member_online_hidden'] = ' ({1} member был невидимы)';
$l['members_online_hidden'] = ' ({1} members были невидимы)';
$l['rating_thread'] = 'Рейтинг темы';
$l['viewing_imcenter'] = 'Проосмотр IM центра';
$l['managing_favorites'] = 'Управление тем в закладках';
$l['managing_subscriptions'] = 'Управление подписками на темы';
$l['managing_group'] = 'Управление группами пользователей';
$l['viewing_modcp'] = 'Просмотр контр.панели модератора';
$l['viewing_modlogs'] = 'Просмотр Moderator Logs';
$l['managing_announcements'] = 'Управление объявлениями';
$l['search_for_user'] = 'Поиск пользователей';
$l['managing_warninglogs'] = 'Управление логами предупреждений';
$l['searching_ips'] = 'Поиск IP';
$l['viewing_reports'] = 'Viewing Reported Posts';
$l['adding_announcement'] = 'Добавление Объявления';
$l['deleting_announcement'] = 'Удаление Объявления';
$l['editing_announcement'] = 'Удаление Объявления';
$l['managing_modqueue'] = 'Управление очередью для модерации';
$l['editing_user_profiles'] = 'Редактирование профиля пользователя';
$l['managing_bans'] = 'Управление банами';
$l['revoking_warning'] = 'Аннулирование предупреждения';
$l['warning_user'] = 'Предупреждение пользователю';
$l['viewing_warning'] = 'Просмотр предупреждений';
$l['managing_warnings'] = 'Управление предупреждениями';
$l['changing_dst'] = 'Изменить на летнее время';
$l['printing_thread'] = 'Печать темы';
$l['printing_thread2'] = 'Печать темы <a href="{1}">{2}</a>';
$l['managing_buddyignorelist'] = 'Управление списком Друзья/Игнор ';
